// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffgbpdfpgicgucmpqdsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZ2JwZGZwZ2ljZ3VjbXBxZHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjY0NDIsImV4cCI6MjA2MzMwMjQ0Mn0.Uy4vXJRQ7nIVP8e78Mmm4w7r2LkzyqOgOOA1I3j4UUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);